# Generated by Django 4.2.4 on 2023-08-06 11:16

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=54, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=54, unique=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='invoices.category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Title')),
                ('slug', models.SlugField(blank=True, max_length=64, unique=True)),
                ('money_transaction', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Income/Outcome')),
                ('currency', models.CharField(choices=[('₴', 'hryvnia'), ('$', 'dollar'), ('€', 'euro')], max_length=1)),
                ('date_created', models.DateField(auto_now_add=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.category')),
            ],
            options={
                'verbose_name_plural': 'Invoices',
                'ordering': ('-date_created',),
            },
        ),
    ]
