# Generated by Django 4.2.4 on 2023-10-26 20:49

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=54, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=54, unique=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='invoices.category')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='Title')),
                ('operation', models.CharField(choices=[('income', 'income'), ('expense', 'expense')], max_length=7, verbose_name='operation')),
                ('value', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='money_value')),
                ('currency', models.CharField(choices=[('UAH', '₴'), ('USD', '$'), ('EUR', '€')], max_length=3, verbose_name='currency')),
                ('date_created', models.DateField(auto_now_add=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoices.category')),
            ],
            options={
                'verbose_name_plural': 'Invoices',
                'ordering': ['-date_created'],
            },
        ),
    ]
