# Generated by Django 4.2.4 on 2023-11-09 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='currency',
            field=models.CharField(choices=[('₴', '₴'), ('$', '$'), ('€', '€')], max_length=3, verbose_name='currency'),
        ),
    ]
