# Generated by Django 4.2.4 on 2023-08-07 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_remove_invoice_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoices.category'),
        ),
    ]
