# Generated by Django 4.2.4 on 2023-11-13 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_alter_invoice_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='Title')),
                ('operation', models.CharField(choices=[('income', 'income'), ('expense', 'expense')], max_length=7, verbose_name='operation')),
                ('value', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='value')),
                ('currency', models.CharField(choices=[('₴', '₴'), ('$', '$'), ('€', '€')], max_length=3, verbose_name='currency')),
                ('date_created', models.DateField(auto_now_add=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoices.category')),
            ],
            options={
                'verbose_name_plural': 'Transactions',
                'ordering': ['-date_created'],
            },
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
    ]
