# Generated by Django 4.2.4 on 2023-09-12 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_alter_invoice_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
