# Generated by Django 4.2.4 on 2023-09-12 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_alter_category_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='money_transaction',
        ),
        migrations.AddField(
            model_name='invoice',
            name='operation',
            field=models.DecimalField(decimal_places=2, default=0.1, max_digits=7, verbose_name='Operation'),
            preserve_default=False,
        ),
    ]
