# Generated by Django 4.2.4 on 2023-12-06 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_transaction_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='currency',
            field=models.CharField(choices=[('UAH', '₴'), ('USD', '$'), ('EUR', '€')], max_length=3, verbose_name='currency'),
        ),
    ]
