# Generated by Django 4.2.4 on 2023-09-13 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0005_remove_invoice_money_transaction_invoice_operation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-date_created'], 'verbose_name_plural': 'Invoices'},
        ),
    ]
