# Generated by Django 4.2.4 on 2023-12-21 20:50

from django.db import migrations, models
import invoices.models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0006_alter_transaction_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, default='invoices/img/category/default_category_img.svg', null=True, upload_to=invoices.models.category_image_path),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('name', 'slug')},
        ),
    ]
