# Generated by Django 4.2.4 on 2023-12-21 21:41

from django.db import migrations, models
import invoices.models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0007_category_image_alter_category_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, default='media/invoices/category/category_custom_img/entertainment/test.png', null=True, upload_to=invoices.models.category_image_path),
        ),
    ]
