# Generated by Django 4.2.4 on 2024-02-21 12:31

from django.db import migrations, models
import invoices.models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0008_alter_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, default='invoices/category/default_category_img.svg', null=True, upload_to=invoices.models.category_image_path),
        ),
    ]
