# Generated by Django 4.2.4 on 2024-07-05 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0015_category_is_default'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-date_purchased'], 'verbose_name_plural': 'Transactions'},
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='date_created',
        ),
        migrations.AddField(
            model_name='transaction',
            name='date_purchased',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
