# Generated by Django 4.2.4 on 2024-02-26 12:20

import accounts.models
from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default='accounts/default_profile_avatar.svg', force_format='WEBP', keep_meta=True, null=True, quality=95, scale=0.5, size=[500, 500], upload_to=accounts.models.profile_avatar_path),
        ),
    ]
