# Generated by Django 4.2.4 on 2024-02-27 13:30

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_profile_avatar_thumbnail_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar_thumbnail',
            field=models.ImageField(blank=True, null=True, storage=accounts.models.OverwriteStorage()),
        ),
    ]
