# Generated by Django 4.2.4 on 2024-02-27 15:14

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_profile_avatar_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar_thumbnail',
            field=models.ImageField(blank=True, null=True, storage=accounts.models.OverwriteStorage(), upload_to=''),
        ),
    ]
