# Generated by Django 4.2.4 on 2024-02-27 15:26

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_profile_avatar_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.profile_avatar_thumbnail_path),
        ),
    ]
