# Generated by Django 4.2.4 on 2023-12-06 21:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('preferences', '0002_rename_profile_config_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='currency',
            field=models.CharField(choices=[('UAH', '₴'), ('USD', '$'), ('EUR', '€')], default='USD', max_length=3),
        ),
        migrations.AlterField(
            model_name='config',
            name='language',
            field=models.CharField(choices=[('EN', 'English'), ('UA', 'Ukrainian')], default='EN', max_length=56),
        ),
        migrations.AlterField(
            model_name='config',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config', to=settings.AUTH_USER_MODEL),
        ),
    ]
